### ISSUE TITLE
Add support of candran [preprocessor]

### ISSUE THREAD

**Issue by ZwerOxotnik** [ZwerOxotnik/factorio-example-mod#4]
[Candran](https://github.com/Reuh/candran) - a Lua dialect and simple preprocessor

**Comment by ZwerOxotnik** [comment]
```yaml
- uses: leafo/gh-actions-lua@v8
  with:
    luaVersion: "5.2.1"
- uses: leafo/gh-actions-luarocks@v4
  with:
    luarocksVersion: "3.7.0"
- name: install a module
  run: luarocks install candran
```

  
Welp, I'm going to use [https://github.com/marketplace/actions/factorio-publish-mod-action](https://github.com/marketplace/actions/factorio-publish-mod-action) also

I need to write some scripts, and it'll be usable, although it's quite hard for me to use that on any OS...
